INSERT INTO VALORES_PAGAMENTO (ID, TIPO_PLANO_PAGAMENTO, VALOR) VALUES('1','MENSAL', 75.00);
INSERT INTO VALORES_PAGAMENTO (ID, TIPO_PLANO_PAGAMENTO, VALOR) VALUES('2','TRIMESTRAL', 202.50);
INSERT INTO VALORES_PAGAMENTO (ID, TIPO_PLANO_PAGAMENTO, VALOR) VALUES('3','SEMESTRAL', 391.00);
INSERT INTO VALORES_PAGAMENTO (ID, TIPO_PLANO_PAGAMENTO, VALOR) VALUES('4','ANUAL', 756.0);

INSERT INTO PERFIL(id, nome) VALUES(1, 'ROLE_ADM');
INSERT INTO PERFIL(id, nome) VALUES(2, 'ROLE_PERSONAL');
INSERT INTO PERFIL(id, nome) VALUES(3, 'ROLE_ALUNO');